### ISSUE TITLE
gitsigns.nvim blame virtual text not displaying

### ISSUE THREAD

**Issue by gnoeyp** [oxfist/night-owl.nvim#19] opened 2023-10-05 16:30 UTC
I'm trying to use this theme and [git signs](https://github.com/lewis6991/gitsigns.nvim) for line blame. A virtual text is supposed to be shown but I only see an icon with no text (as the picture shows below). Is it possible to customize the color scheme to fix this, or do you have any plan to update for supporting git signs?

![스크린샷 2023-10-06 오전 1 19 50](https://github.com/oxfist/night-owl.nvim/assets/62169778/fac8a0de-f527-489f-9002-96a52ab3346f)

**Comment by oxfist** [comment] 2023-10-05 17:22
Hi @gnoeyp! Gitsigns should definitely work so I might have messed up a highlight group. Happy to help get this fixed for you.

Can you tell me what's the output when you run `:verbose hi GitSignsCurrentLineBlame` and `:verbose hi NonText` inside neovim?

**Comment by gnoeyp** [comment] 2023-10-06 01:06
This is the output! Thank you :)
![스크린샷 2023-10-06 오전 10 04 34](https://github.com/oxfist/night-owl.nvim/assets/62169778/ae2c9656-cd4e-4ef2-b4f7-905251acc1ff)
![스크린샷 2023-10-06 오전 10 04 48](https://github.com/oxfist/night-owl.nvim/assets/62169778/78b6a20b-fb68-4077-8312-cd0da72e8aa5)

**Comment by oxfist** [comment] 2023-10-13 13:49
@gnoeyp I just pushed a change that explicitly sets the `GitSignsCurrentLineBlame` hl group rather than linking it to `NonText`, can you update the plugin and test on your end if the issue is still there?

**Comment by gnoeyp** [comment] 2023-10-13 14:07
@oxfist I just updated and checked that `GitSignsCurrentLineBlame` color is set. But the issue still appears.

![스크린샷 2023-10-13 오후 11 03 35](https://github.com/oxfist/night-owl.nvim/assets/62169778/755e6b13-b1de-4314-bd63-fff16e6ef2eb)
![스크린샷 2023-10-13 오후 11 08 19](https://github.com/oxfist/night-owl.nvim/assets/62169778/e91fa33e-c0a5-4e0c-bfa4-55fde173c8e8)

**Comment by oxfist** [comment] 2023-10-13 14:14
@gnoeyp Thanks for the update! Sorry the issue is still there, I have three requests 🙏🏼 :

1. Can you see the blame text after running the following? `:hi GitSignsCurrentLineBlame guifg=red`
2. Can you tell me which Neovim version you're running from the output of `nvim --version`? 
3. Can you test if you can see the blame text by disabling all plugins except for this theme? I'm unsure what the root cause of this issue is but it is possible that it's being caused by other plugin

**Comment by gnoeyp** [comment] 2023-10-13 15:54
I see the blame text if I set `:hi GitSignsCurrentLineBlame guifg=red`. I think it's because blame text has the same color with background (#011627).

**Comment by gnoeyp** [comment] 2023-10-13 15:59
Maybe it should be `visual = "#1d3b53"` ?

**Comment by oxfist** [comment] 2023-10-13 16:44
I think you might be on the right track. I understand why this might be happening if `GitSignsCurrentLuneBlame` and the background are the exact same value, BUT `CursorLine`, which represents the active line, is set to a darker background to provide visual feedback of the line you're in. This is the original's theme default behavior.

What do you get with `:hi CursorLine`?

Also, can you share your gitsigns config here so I can try and reproduce your issue?

**Comment by oxfist** [comment] 2023-10-13 16:54
I suspect you might not have `cursorline` enabled, you can try what you see on the blame line with `:set cursorline`. Although this shouldn't be required I think there might be still an issue.

I just ran `:hi GitSignsCurrentLineBlame guifg=red guibg=red` and see this, so I'm confident there's something messing up with the opacity or color of that hl group, since you can still see the text in the screenshot below:

<img width="1007" alt="CleanShot 2023-10-13 at 1 53 23@2x" src="https://github.com/oxfist/night-owl.nvim/assets/934679/f809988c-e8c6-4f33-99fb-17fcd86e5082">

**Comment by oxfist** [comment] 2023-11-08 17:35
@gnoeyp I was able to reproduce this consistently after disabling some transparency settings in my terminal 🤦🏼 Sorry about that! It should be fixed now

**Closed as completed** 2023-11-08 17:34 UTC
Labels: highlight issue

**Comment by oxfist** [comment] 2023-11-08 17:36
@all-contributors please add @gnoeyp for bug
